/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 140005
 Source Host           : localhost:5432
 Source Catalog        : testdb
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140005
 File Encoding         : 65001

 Date: 03/09/2022 07:41:39
*/


-- ----------------------------
-- Table structure for mainApp_product
-- ----------------------------
DROP TABLE IF EXISTS "public"."mainApp_product";
CREATE TABLE "public"."mainApp_product" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "order_number" int4 NOT NULL,
  "cost" float8 NOT NULL,
  "delivery_time" date NOT NULL,
  "cost_in_rub" float8 NOT NULL
)
;

-- ----------------------------
-- Primary Key structure for table mainApp_product
-- ----------------------------
ALTER TABLE "public"."mainApp_product" ADD CONSTRAINT "mainApp_product_pkey" PRIMARY KEY ("id");
