# Generated by Django 4.1 on 2022-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('cost', models.FloatField()),
                ('delivery_time', models.DateField()),
                ('cost_in_rub', models.FloatField()),
            ],
        ),
    ]
