# Generated by Django 4.1 on 2022-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_overdue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overdue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('message_sent', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='overdue',
        ),
    ]
